version: '3'

services:
  app:
    image: 'bitnami/symfony'
    ports:
      - '80:8000'
    volumes:
      - '.:/app'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - SYMFONY_DATABASE_HOST=mariadb
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=symfony
      - SYMFONY_DATABASE_NAME=symfony
      - SYMFONY_DATABASE_PASSWORD=symfony
    depends_on:
      - mariadb

  mariadb:
    image: 'bitnami/mariadb:10.6'
    ports:
      - '3306:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=symfony
      - MARIADB_PASSWORD=symfony
      - MARIADB_DATABASE=symfony